import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

// Importation du composant ModalProvider depuis le contexte modal
import { ModalProvider } from "@/context/modal-context.js";

// Importation du composant ThemeProvider depuis le contexte de thème
import { ThemeProvider } from "@/context/theme-context.js";
import ReduxProvider from "@/redux/ReduxProvider";
// import Navbar from "@/sections/navbar/Navbar";

export const metadata = {
  title: "Amine's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={montserrat.className}>
        <div id="overlays"></div>
        {
          <ReduxProvider>
            <ThemeProvider>
              <ModalProvider>
                {/* <Navbar /> */}
                {children}
              </ModalProvider>
            </ThemeProvider>
          </ReduxProvider>
        }
      </body>
    </html>
  );
}
